### ISSUE TITLE
Update photos for social media

### ISSUE THREAD

**Issue by dahacouk** [collabcamp/collabcamp#2]
@Dorotea please update photos for social media.

Here's a list of the sites we have so far. If there are any others just edit this post and add them in the list! ;-)
- [x] https://plus.google.com/+collabcamp
- [x] https://www.youtube.com/c/collabcamp
- [x] https://www.facebook.com/collabcamp
- [ ] http://collab.camp
- [x] https://github.com/collabcamp
- [x] https://www.facebook.com/groups/collabcamp/

**Comment by Dorotea** [comment]
added a facebook group to the list too

I updated the cover photos of the facebook page and the group and google plus page and youtube channel
now finding a good way to redesign the profile avatar so it remains somewhat readable in its small version too

**Comment by Dorotea** [comment]
updated all social media, covers and profile avatars

**Comment by Dorotea** [comment]
( we also need twitter / as a side comment , but we can add it to future social media list , when we can get our desired twitter name ) 

( it would be nice if we could fork to-do discussions here somehow )
