### ISSUE TITLE
Change Twitter account name and username

### ISSUE THREAD

**Issue by dahacouk** [collabcamp/collabcamp#4]
Suggest changing Twitter account:
- Name: CollabCamp
- Username: collabcamp1

But must be logged into Medium before we make the change and then update both at the same time.

And @Dorotea updating photos would be cool.

Note we are still trying to get [@collabcamp](https://twitter.com/collabcamp).

Let's agree this (or not) in the next Hangout.

**Comment by Dorotea** [comment]
( checking if it will add participants )

**Comment by dahacouk** [comment]
At least for the moment we have changed the Twitter account to [@collabcamps](https://twitter.com/collabcamps).
