### ISSUE TITLE
Managing sign ups

### ISSUE THREAD

**Issue by mozboz** [collabcamp/collabcamp#9]
Need a system to manage signups, across different platforms and for people who don't want to use e.g. Facebook, Google.

**Comment by mozboz** [comment]
potential features:
- register for the event
- add more information about your project - URL, description
- add information about what you want from the event
- channel to receive communication back from event, and from other participants

**Comment by mozboz** [comment]
Although this is a big task, we have some potential to lead here in terms of shared data and personally owned data, using something like the Personal Linked Profiles project to setup transportable profiels for everyone who signs up. 

https://github.com/hackers4peace/plp-docs

**Comment by mozboz** [comment]
See data we want to capture about each attendee here:

https://docs.google.com/spreadsheets/d/1ltIt2SSgZ9zZ5YPfr9atYs1C4uQ29W-yVp7R1WvQxqw/edit#gid=484110814

**Comment by dahacouk** [comment]
Please take a look at the proposed registration form and give feedback! https://docs.google.com/forms/d/1TQr0bVWU1YjK7ijHk_XT0wsKt21V5f_r8TvNhbLgZiE/viewform @collabcamp/owners
